[site]
title = "Zongyuan Deng"
description = "Recent Master’s Graduate, University of Nottingham Ningbo China"
favicon = "/favicon.svg"
last_updated = "Feb 26, 2026"

[author]
name = "Zongyuan Deng"
title = "Recent Master’s Graduate"
institution = "University of Nottingham Ningbo China"
avatar = "/bio.jpg"

[social]
# Contact information (leave blank or delete to hide)

email = "dzy3991005.com"
location = "Tianjin, China"
location_url = "https://maps.google.com"
location_details = [
  "Room 123, Science Building,",
  "University Avenue, City, Country"
]
google_scholar = "https://scholar.google.com"
orcid = "https://orcid.org/0009-0009-4300-5358"
github = "https://github.com"
linkedin = "https://www.linkedin.com/in/zongyuan-castiel-deng/"

[features]
# Show a like button on the about page
enable_likes = true

# Display all subpages on a single page
enable_one_page_mode = false

[i18n]
enabled = true
locales = ["zh", "en"]
default_locale = "en"
# "auto" means the locale will be determined by the browser's language setting, "fixed" means the locale will be fixed to the default locale (but can be switched still, if you want to disable, set "enable=false")
mode = "auto"
fixed_locale = "en"
# If true, PRISM will remember user's language preference in browser's localStorage
persist = true
# Show a language switcher on the top right corner
switcher = true

[i18n.labels]
zh = "中文"
en = "English"

[[navigation]]
title = "About"
type = "page"
target = "about"
href = "/"

[[navigation]]
title = "Research"       
type = "page"              
target = "research"       
href = "/research"        


[[navigation]]
title = "CV"         
type = "external"     
target = "_blank"    
href = "/cv_zongyuan_deng.pdf"  
